config:
  packages:
    yum:
      ruby: []
  files:
    /home/ec-user/install:
      source:
  services:
    sysvinit:
      codedeploy-agent:
        enabled: true
        ensureRunning: true
      influxdb:
        enabled: true
        ensureRunning: true
      telegraf:
        enabled: true
        ensureRunning: true
      kapacitor:
        enabled: true
        ensureRunning: true
      chronograf:
        enabled: false
        ensureRunning: false